"""add status to attendance

Revision ID: 50e2ea4b0499
Revises: 8581cdb5e7ef
Create Date: 2026-05-02 20:38:17.632880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50e2ea4b0499'
down_revision: Union[str, Sequence[str], None] = '8581cdb5e7ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('status', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendance', 'status')
    # ### end Alembic commands ###
